version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/node:18.3.0
    
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: npm i 
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint

  test:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys: 
          -  "npm-packages"
      - run: npm i 
      - run: npm run test 
  
  analyze:
    executor: my-executor
    steps:
      - checkout
      - run: npm audit  

workflows:
  btd:
    jobs:
      - build 
      - test:
          requires:
            - build 
      - analyze: 
          requires:
            - test
